namespace PassSafe.Models
{
    /// <summary>
    /// Represents a critical security warning generated by the Password Analyzer.
    /// Guides the user to fix reused or very weak passwords.
    /// </summary>
    public class CriticalAction
    {
        public string Title { get; set; }

        public string Description { get; set; }

        public string IconKey { get; set; }

        public string Color { get; set; }

        /// <summary>
        /// Holds the reference to the actual password object so it can be edited directly from the analyzer screen.
        /// </summary>
        public Password TargetPassword { get; set; }
    }
}